issues:
  exclude-dirs:
    - lib
  exclude-files:
    - xxhash.go
  exclude-rules:
    - path: token.go
      linters:
        - errcheck
    - path: escape.go
      linters:
        - errcheck

    - linters:
        - typecheck
      text: "syscall/js"
    - linters:
        - staticcheck
      text: "SA9003"
    - linters:
        - typecheck
      text: "by package vert"
    - linters:
        - typecheck
      text: "vert."
